(lang dune 3.24)

(name todo)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <Arpit>")

(maintainers "Maintainer Name <arpit8x.dev@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name todo)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
